server:
  port: 8081

spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:tcp://localhost/~/walkmate
    url: jdbc:h2:mem:walkmate
    username: greytomato
    password: 1234
  jpa:
    open-in-view: true
    hibernate:
      #ddl-auto: update
      ddl-auto: create
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  security:
    user:
      name: test
      password: 1234
logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace